CREATE TABLE `corp`.`md_contacts` (
  `CONTACT_ID` INT NOT NULL AUTO_INCREMENT,
  `CONTACT_NAME` VARCHAR(250) NOT NULL,
  `CONTACT_NUMBER` INT NOT NULL,
  `CONTACT_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`CONTACT_ID`),
  UNIQUE INDEX `CONTACT_ID_UNIQUE` (`CONTACT_ID` ASC));