package net.corp.core.model;

// Generated 21 May, 2014 12:30:42 PM by Hibernate Tools 4.0.0

/**
 * MdConversion generated by hbm2java
 */
@SuppressWarnings("serial")
public class Conversion implements java.io.Serializable {

	private Integer conversionId;
	private String fromUnit;
	private String toUnit;
	private String factor;
	private String unitType;

	public Conversion() {
	}

	public Conversion(String fromUnit, String toUnit, String factor,
			String unitType) {
		this.fromUnit = fromUnit;
		this.toUnit = toUnit;
		this.factor = factor;
		this.unitType = unitType;
	}

	public Integer getConversionId() {
		return this.conversionId;
	}

	public void setConversionId(Integer conversionId) {
		this.conversionId = conversionId;
	}

	public String getFromUnit() {
		return this.fromUnit;
	}

	public void setFromUnit(String fromUnit) {
		this.fromUnit = fromUnit;
	}

	public String getToUnit() {
		return this.toUnit;
	}

	public void setToUnit(String toUnit) {
		this.toUnit = toUnit;
	}

	public String getFactor() {
		return this.factor;
	}

	public void setFactor(String factor) {
		this.factor = factor;
	}

	public String getUnitType() {
		return this.unitType;
	}

	public void setUnitType(String unitType) {
		this.unitType = unitType;
	}

}
