package net.corp.core.model;

// Generated 21 May, 2014 12:30:42 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * DExpenditure generated by hbm2java
 */
@SuppressWarnings("serial")
public class Expenditure implements java.io.Serializable {

	private Long itemid;
	private String mainitemid;
	private String itemname;
	private String itemdesc;
	private String unit;
	private Double rate;
	private Double qty;
	private Double amount;
	private Date dt;

	public Expenditure() {
	}

	public Expenditure(String mainitemid, String itemname, String itemdesc,
			String unit, Double rate, Double qty, Double amount,
			Date dt) {
		this.mainitemid = mainitemid;
		this.itemname = itemname;
		this.itemdesc = itemdesc;
		this.unit = unit;
		this.rate = rate;
		this.qty = qty;
		this.amount = amount;
		this.dt = dt;
	}

	public Long getItemid() {
		return this.itemid;
	}

	public void setItemid(Long itemid) {
		this.itemid = itemid;
	}

	public String getMainitemid() {
		return this.mainitemid;
	}

	public void setMainitemid(String mainitemid) {
		this.mainitemid = mainitemid;
	}

	public String getItemname() {
		return this.itemname;
	}

	public void setItemname(String itemname) {
		this.itemname = itemname;
	}

	public String getItemdesc() {
		return this.itemdesc;
	}

	public void setItemdesc(String itemdesc) {
		this.itemdesc = itemdesc;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	public Double getQty() {
		return this.qty;
	}

	public void setQty(Double qty) {
		this.qty = qty;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public Date getDt() {
		return this.dt;
	}

	public void setDt(Date dt) {
		this.dt = dt;
	}

}
