package net.corp.core.model;

// Generated 21 May, 2014 12:30:42 PM by Hibernate Tools 4.0.0

/**
 * DHdd generated by hbm2java
 */
@SuppressWarnings("serial")
public class Hdd implements java.io.Serializable {

	private Integer id;
	private String hddno;

	public Hdd() {
	}

	public Hdd(String hddno) {
		this.hddno = hddno;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getHddno() {
		return this.hddno;
	}

	public void setHddno(String hddno) {
		this.hddno = hddno;
	}

}
