package net.corp.core.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

// Generated 21 May, 2014 12:30:42 PM by Hibernate Tools 4.0.0

/**
 * MdItemMain generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@DynamicInsert(true)
@DynamicUpdate(true)
@Table(name="md_item_main")
public class Items implements java.io.Serializable {

	@Id
	@Column(name = "main_itemid")
	@GeneratedValue
	private Integer mainItemid;
	
	@Column(name = "main_itemname")
	private String mainItemname;
	
	@Column(name = "usrid")
	private Integer usrid;
	
	@Column(name = "factor")
	private Double factor;
	
	@Column(name = "trans_rate")
	private Double transRate;
	
	@Column(name = "IN_ADDL_IND")
	private boolean inAddlInd;
	
	@Column(name = "OUT_ADDL_IND")
	private boolean outAddlInd;
	
	@Column(name = "HEIGHT_CORRECTION_IND")
	private boolean htCorrectionInd;
	
	@Column(name = "QUANTITY_IND")
	private boolean qtyInd;
	
	@Column(name = "KL_IND")
	private boolean klInd;
	
	@Column(name = "INVOICE_IND")
	private boolean invoiceInd;
	
	public Integer getMainItemid() {
		return this.mainItemid;
	}

	public void setMainItemid(Integer mainItemid) {
		this.mainItemid = mainItemid;
	}

	public String getMainItemname() {
		return this.mainItemname;
	}

	public void setMainItemname(String mainItemname) {
		this.mainItemname = mainItemname;
	}

	public Integer getUsrid() {
		return this.usrid;
	}

	public void setUsrid(Integer usrid) {
		this.usrid = usrid;
	}

	public Double getFactor() {
		return this.factor;
	}

	public void setFactor(Double factor) {
		this.factor = factor;
	}

	public Double getTransRate() {
		return this.transRate;
	}

	public void setTransRate(Double transRate) {
		this.transRate = transRate;
	}

	public boolean isInAddlInd() {
		return inAddlInd;
	}

	public void setInAddlInd(boolean inAddlInd) {
		this.inAddlInd = inAddlInd;
	}

	public boolean isOutAddlInd() {
		return outAddlInd;
	}

	public void setOutAddlInd(boolean outAddlInd) {
		this.outAddlInd = outAddlInd;
	}

	public boolean isHtCorrectionInd() {
		return htCorrectionInd;
	}

	public void setHtCorrectionInd(boolean htCorrectionInd) {
		this.htCorrectionInd = htCorrectionInd;
	}

	public boolean isQtyInd() {
		return qtyInd;
	}

	public void setQtyInd(boolean qtyInd) {
		this.qtyInd = qtyInd;
	}

	public boolean isKlInd() {
		return klInd;
	}

	public void setKlInd(boolean klInd) {
		this.klInd = klInd;
	}

	public boolean isInvoiceInd() {
		return invoiceInd;
	}

	public void setInvoiceInd(boolean invoiceInd) {
		this.invoiceInd = invoiceInd;
	}

}
