package net.corp.core.model;

// Generated 21 May, 2014 12:30:42 PM by Hibernate Tools 4.0.0

/**
 * DNotificationsTemp generated by hbm2java
 */
@SuppressWarnings("serial")
public class NotificationsTemp implements java.io.Serializable {

	private Integer id;
	private String mobno;
	private String msgtext;
	private Long challanNo;

	public NotificationsTemp() {
	}

	public NotificationsTemp(String mobno, String msgtext, Long challanNo) {
		this.mobno = mobno;
		this.msgtext = msgtext;
		this.challanNo = challanNo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMobno() {
		return this.mobno;
	}

	public void setMobno(String mobno) {
		this.mobno = mobno;
	}

	public String getMsgtext() {
		return this.msgtext;
	}

	public void setMsgtext(String msgtext) {
		this.msgtext = msgtext;
	}

	public Long getChallanNo() {
		return this.challanNo;
	}

	public void setChallanNo(Long challanNo) {
		this.challanNo = challanNo;
	}

}
