package net.corp.core.model;

// Generated 21 May, 2014 12:30:42 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * DOrders generated by hbm2java
 */
@SuppressWarnings("serial")
public class Orders implements java.io.Serializable {

	private Integer orderId;
	private Date orderIssueDate;
	private Date orderDispatchDate;
	private String orderExtNo;
	private Date createdDate;
	private Date updatedDate;
	private int createdBy;
	private int updatedBy;

	public Orders() {
	}

	public Orders(Date orderIssueDate, Date orderDispatchDate,
			Date createdDate, Date updatedDate, int createdBy, int updatedBy) {
		this.orderIssueDate = orderIssueDate;
		this.orderDispatchDate = orderDispatchDate;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
	}

	public Orders(Date orderIssueDate, Date orderDispatchDate,
			String orderExtNo, Date createdDate, Date updatedDate,
			int createdBy, int updatedBy) {
		this.orderIssueDate = orderIssueDate;
		this.orderDispatchDate = orderDispatchDate;
		this.orderExtNo = orderExtNo;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Date getOrderIssueDate() {
		return this.orderIssueDate;
	}

	public void setOrderIssueDate(Date orderIssueDate) {
		this.orderIssueDate = orderIssueDate;
	}

	public Date getOrderDispatchDate() {
		return this.orderDispatchDate;
	}

	public void setOrderDispatchDate(Date orderDispatchDate) {
		this.orderDispatchDate = orderDispatchDate;
	}

	public String getOrderExtNo() {
		return this.orderExtNo;
	}

	public void setOrderExtNo(String orderExtNo) {
		this.orderExtNo = orderExtNo;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public int getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(int updatedBy) {
		this.updatedBy = updatedBy;
	}

}
