package net.corp.core.model;

// Generated 21 May, 2014 12:30:42 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * DPlantSpare generated by hbm2java
 */
public class PlantSpare implements java.io.Serializable {

	private Long itemid;
	private String mainitemid;
	private String itemname;
	private String itemdesc;
	private String unit;
	private BigDecimal rate;
	private BigDecimal qty;
	private BigDecimal amount;
	private Date dt;
	private Long challanNo;
	private Integer vendorId;

	public PlantSpare() {
	}

	public PlantSpare(BigDecimal rate) {
		this.rate = rate;
	}

	public PlantSpare(String mainitemid, String itemname, String itemdesc,
			String unit, BigDecimal rate, BigDecimal qty, BigDecimal amount,
			Date dt, Long challanNo, Integer vendorId) {
		this.mainitemid = mainitemid;
		this.itemname = itemname;
		this.itemdesc = itemdesc;
		this.unit = unit;
		this.rate = rate;
		this.qty = qty;
		this.amount = amount;
		this.dt = dt;
		this.challanNo = challanNo;
		this.vendorId = vendorId;
	}

	public Long getItemid() {
		return this.itemid;
	}

	public void setItemid(Long itemid) {
		this.itemid = itemid;
	}

	public String getMainitemid() {
		return this.mainitemid;
	}

	public void setMainitemid(String mainitemid) {
		this.mainitemid = mainitemid;
	}

	public String getItemname() {
		return this.itemname;
	}

	public void setItemname(String itemname) {
		this.itemname = itemname;
	}

	public String getItemdesc() {
		return this.itemdesc;
	}

	public void setItemdesc(String itemdesc) {
		this.itemdesc = itemdesc;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public Date getDt() {
		return this.dt;
	}

	public void setDt(Date dt) {
		this.dt = dt;
	}

	public Long getChallanNo() {
		return this.challanNo;
	}

	public void setChallanNo(Long challanNo) {
		this.challanNo = challanNo;
	}

	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

}
