package net.corp.core.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

// Generated 21 May, 2014 12:30:42 PM by Hibernate Tools 4.0.0

/**
 * MdPrimaryGroup generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@DynamicInsert(true)
@DynamicUpdate(true)
@Table(name="md_primary_group")
public class PrimaryGroup implements java.io.Serializable {

	@Id
	@GeneratedValue
	@Column(name = "Vendor_id")
	private Integer vendorId;
	@Column(name = "vendor_name")
	private String vendorName;
	@Column(name = "address")
	private String address;
	@Column(name = "phone_no")
	private String phoneNo;
	@Column(name = "year_id")
	private Integer yearId;
	@Column(name = "Given_code")
	private String givenCode;
	@Column(name = "number")
	private String number;
	@Column(name = "usrid")
	private Integer usrid;
	@Column(name = "persentage")
	private Double percentage;

	public PrimaryGroup() {
	}

	public PrimaryGroup(String vendorName, String address, String phoneNo,
			Integer yearId, String givenCode, String number, Integer usrid,
			Double percentage) {
		this.vendorName = vendorName;
		this.address = address;
		this.phoneNo = phoneNo;
		this.yearId = yearId;
		this.givenCode = givenCode;
		this.number = number;
		this.usrid = usrid;
		this.percentage = percentage;
	}

	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	public String getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	public Integer getYearId() {
		return this.yearId;
	}

	public void setYearId(Integer yearId) {
		this.yearId = yearId;
	}

	public String getGivenCode() {
		return this.givenCode;
	}

	public void setGivenCode(String givenCode) {
		this.givenCode = givenCode;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public Integer getUsrid() {
		return this.usrid;
	}

	public void setUsrid(Integer usrid) {
		this.usrid = usrid;
	}

	public Double getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Double percentage) {
		this.percentage = percentage;
	}

}
