package net.corp.core.model;

// Generated 21 May, 2014 12:30:42 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * DReports generated by hbm2java
 */
public class Reports implements java.io.Serializable {

	private Integer reportId;
	private String reportName;
	private String reportUrl;
	private Date createdDate;
	private int createdBy;

	public Reports() {
	}

	public Reports(String reportName, String reportUrl, Date createdDate,
			int createdBy) {
		this.reportName = reportName;
		this.reportUrl = reportUrl;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	public Integer getReportId() {
		return this.reportId;
	}

	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	public String getReportName() {
		return this.reportName;
	}

	public void setReportName(String reportName) {
		this.reportName = reportName;
	}

	public String getReportUrl() {
		return this.reportUrl;
	}

	public void setReportUrl(String reportUrl) {
		this.reportUrl = reportUrl;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

}
