package net.corp.core.model;

// Generated 21 May, 2014 12:30:42 PM by Hibernate Tools 4.0.0

/**
 * MdUserData generated by hbm2java
 */
@SuppressWarnings("serial")
public class UserData implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String pass;
	private Boolean add;
	private Boolean edit;
	private Boolean delete;
	private Boolean userAdmin;
	private Boolean offline;
	private String usrid;
	private Boolean updateinvoice;

	public UserData() {
	}

	public UserData(String userName, String pass, Boolean add, Boolean edit,
			Boolean delete, Boolean userAdmin, Boolean offline, String usrid,
			Boolean updateinvoice) {
		this.userName = userName;
		this.pass = pass;
		this.add = add;
		this.edit = edit;
		this.delete = delete;
		this.userAdmin = userAdmin;
		this.offline = offline;
		this.usrid = usrid;
		this.updateinvoice = updateinvoice;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public Boolean getAdd() {
		return this.add;
	}

	public void setAdd(Boolean add) {
		this.add = add;
	}

	public Boolean getEdit() {
		return this.edit;
	}

	public void setEdit(Boolean edit) {
		this.edit = edit;
	}

	public Boolean getDelete() {
		return this.delete;
	}

	public void setDelete(Boolean delete) {
		this.delete = delete;
	}

	public Boolean getUserAdmin() {
		return this.userAdmin;
	}

	public void setUserAdmin(Boolean userAdmin) {
		this.userAdmin = userAdmin;
	}

	public Boolean getOffline() {
		return this.offline;
	}

	public void setOffline(Boolean offline) {
		this.offline = offline;
	}

	public String getUsrid() {
		return this.usrid;
	}

	public void setUsrid(String usrid) {
		this.usrid = usrid;
	}

	public Boolean getUpdateinvoice() {
		return this.updateinvoice;
	}

	public void setUpdateinvoice(Boolean updateinvoice) {
		this.updateinvoice = updateinvoice;
	}

}
