package net.corp.core.model;

// Generated 21 May, 2014 12:30:42 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * MdVehicles generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@DynamicInsert(true)
@DynamicUpdate(true)
@Table(name="md_vehicles")
public class Vehicles implements java.io.Serializable {

	@Id
	@Column(name = "VEHICLE_ID")
	@GeneratedValue
	private Integer vehicleId;
	
	@Column(name = "VEHICLE_NUMBER")
	private String vehicleNumber;
	
	@Column(name = "LENGTH")
	private Double length;
	
	@Column(name = "BREADTH")
	private Double breadth;
	
	@Column(name = "HEIGHT")
	private Double height;
	
	@Column(name = "VENDOR_ID")
	private Integer vendorId;
	
	@Column(name = "date_id")
	private Integer dateId;
	
	@Column(name = "VOLUME")
	private Double volume;
	
	@Column(name = "userid")
	private Integer userid;
	
	@Column(name = "dt")
	private Date dt;

	public Vehicles() {
	}

	public Vehicles(String vehicleNumber, Double lenght, Double bredth,
			Double height, Integer vendorId, Integer dateId, Double volume,
			Integer userid, Date dt) {
		this.vehicleNumber = vehicleNumber;
		this.length = lenght;
		this.breadth = bredth;
		this.height = height;
		this.vendorId = vendorId;
		this.dateId = dateId;
		this.volume = volume;
		this.userid = userid;
		this.dt = dt;
	}

	public Integer getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Integer vehicleId) {
		this.vehicleId = vehicleId;
	}

	public String getVehicleNumber() {
		return this.vehicleNumber;
	}

	public void setVehicleNumber(String vehicleNumber) {
		this.vehicleNumber = vehicleNumber;
	}

	public Double getLength() {
		return length;
	}

	public void setLength(Double length) {
		this.length = length;
	}

	public Double getBreadth() {
		return breadth;
	}

	public void setBreadth(Double breadth) {
		this.breadth = breadth;
	}

	public Double getHeight() {
		return this.height;
	}

	public void setHeight(Double height) {
		this.height = height;
	}

	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	public Integer getDateId() {
		return this.dateId;
	}

	public void setDateId(Integer dateId) {
		this.dateId = dateId;
	}

	public Double getVolume() {
		return this.volume;
	}

	public void setVolume(Double volume) {
		this.volume = volume;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Date getDt() {
		return this.dt;
	}

	public void setDt(Date dt) {
		this.dt = dt;
	}

}
