package net.corp.core.model;

// Generated 21 May, 2014 12:30:42 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.*;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * MdVehicles generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@DynamicInsert(true)
@DynamicUpdate(true)
@Table(name="md_vehicles")
public class Vehicles implements java.io.Serializable {

	@Id
	@Column(name = "VEHICLE_ID")
	@GeneratedValue
	private Integer vehicleId;
	
	@Column(name = "VEHICLE_NUMBER")
	private String vehicleNumber;
	
	@Column(name = "LENGTH")
	private Double length;
	
	@Column(name = "BREADTH")
	private Double breadth;
	
	@Column(name = "HEIGHT")
	private Double height;

	@ManyToOne
	@JoinColumn(name = "VENDOR_ID")
	private PrimaryGroup vendor;
	
	@Column(name = "VOLUME")
	private Double volume;
	
	@Column(name = "userid")
	private Integer userId;
	
	public Vehicles() {
	}

	public Vehicles(String vehicleNumber, Double length, Double breadth,
			Double height, PrimaryGroup vendor, Integer dateId, Double volume,
			Integer userId, Date dt) {
		this.vehicleNumber = vehicleNumber;
		this.length = length;
		this.breadth = breadth;
		this.height = height;
		this.vendor = vendor;
		this.volume = volume;
		this.userId = userId;
	}

	public Integer getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Integer vehicleId) {
		this.vehicleId = vehicleId;
	}

	public String getVehicleNumber() {
		return this.vehicleNumber;
	}

	public void setVehicleNumber(String vehicleNumber) {
		this.vehicleNumber = vehicleNumber;
	}

	public Double getLength() {
		return length;
	}

	public void setLength(Double length) {
		this.length = length;
	}

	public Double getBreadth() {
		return breadth;
	}

	public void setBreadth(Double breadth) {
		this.breadth = breadth;
	}

	public Double getHeight() {
		return this.height;
	}

	public void setHeight(Double height) {
		this.height = height;
	}

	public PrimaryGroup getVendor() {
		return this.vendor;
	}

	public void setVendor(PrimaryGroup vendor) {
		this.vendor = vendor;
	}

	public Double getVolume() {
		return this.volume;
	}

	public void setVolume(Double volume) {
		this.volume = volume;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
