package net.corp.core.model;

// Generated 21 May, 2014 12:30:42 PM by Hibernate Tools 4.0.0

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;
import java.util.Date;

/**
 * MdVibhagTypes generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@DynamicInsert(true)
@DynamicUpdate(true)
@Table(name="md_vibhag_types")
public class VibhagTypes implements java.io.Serializable {

	@Id
	@Column(name="VIBHAG_TYPE_ID")
	private int vibhagTypeId;
	@Column(name="VIBHAG_TYPE_NAME")
	private String vibhagTypeName;
	@Column(name="CREATED_BY")
	private Integer createdBy;
	private String sendsms;
	@Column(name="CREATED_DATE")
	private Date createdDate;
	@Column(name="VIBHAG_TYPE_LOOKUP")
	private String vibhagTypeLookup;

	public VibhagTypes() {
	}

	public VibhagTypes(int vibhagTypeId, String vibhagTypeName,
			String vibhagTypeLookup) {
		this.vibhagTypeId = vibhagTypeId;
		this.vibhagTypeName = vibhagTypeName;
		this.vibhagTypeLookup = vibhagTypeLookup;
	}

	public VibhagTypes(int vibhagTypeId, String vibhagTypeName,
			Integer createdBy, String sendsms, Date createdDate,
			String vibhagTypeLookup) {
		this.vibhagTypeId = vibhagTypeId;
		this.vibhagTypeName = vibhagTypeName;
		this.createdBy = createdBy;
		this.sendsms = sendsms;
		this.createdDate = createdDate;
		this.vibhagTypeLookup = vibhagTypeLookup;
	}

	public int getVibhagTypeId() {
		return this.vibhagTypeId;
	}

	public void setVibhagTypeId(int vibhagTypeId) {
		this.vibhagTypeId = vibhagTypeId;
	}

	public String getVibhagTypeName() {
		return this.vibhagTypeName;
	}

	public void setVibhagTypeName(String vibhagTypeName) {
		this.vibhagTypeName = vibhagTypeName;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public String getSendsms() {
		return this.sendsms;
	}

	public void setSendsms(String sendsms) {
		this.sendsms = sendsms;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getVibhagTypeLookup() {
		return this.vibhagTypeLookup;
	}

	public void setVibhagTypeLookup(String vibhagTypeLookup) {
		this.vibhagTypeLookup = vibhagTypeLookup;
	}

}
