package net.corp.core.model;

// Generated 21 May, 2014 12:30:42 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * MdYears generated by hbm2java
 */
public class Years implements java.io.Serializable {

	private Integer dateId;
	private Date dateFrom;
	private Date dateTo;
	private Integer usrid;

	public Years() {
	}

	public Years(Date dateFrom, Date dateTo, Integer usrid) {
		this.dateFrom = dateFrom;
		this.dateTo = dateTo;
		this.usrid = usrid;
	}

	public Integer getDateId() {
		return this.dateId;
	}

	public void setDateId(Integer dateId) {
		this.dateId = dateId;
	}

	public Date getDateFrom() {
		return this.dateFrom;
	}

	public void setDateFrom(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	public Date getDateTo() {
		return this.dateTo;
	}

	public void setDateTo(Date dateTo) {
		this.dateTo = dateTo;
	}

	public Integer getUsrid() {
		return this.usrid;
	}

	public void setUsrid(Integer usrid) {
		this.usrid = usrid;
	}

}
