package net.corp.core.constants;

public interface CorpConstants {
	String STATUS_MATERIAL_ENTRY_INITIATED = "INITIATED";
	String STATUS_MATERIAL_ENTRY_COMPLETED = "COMPLETED";
	String STATUS_MATERIAL_ENTRY_CANCELLED = "CANCELLED";
	String STATUS_MATERIAL_ENTRY_LOCKED = "LOCKED";
	
}
